### ISSUE TITLE
Keeps outputting error message: trying to get `color` from undefined object

### ISSUE THREAD

**Issue by lethefrost** [neodisk17/vscode-ext-flutter-color-viewer#47]
It outputs the following messages to the output - extension host channel almost every second:

(v1.2.3 updated on Apr. 20, macOS Sonoma 14.4.1, VSC 1.88.1)

```js
[error] [circlecodesolution.ccs-flutter-color] provider FAILED
[error] TypeError: Cannot read properties of undefined (reading 'color')
    at t.default.provideDocumentColors (/Users/username/.vscode/extensions/circlecodesolution.ccs-flutter-color-1.2.3/dist/extension.js:2:1379)
    at se.provideColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:113994)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:130551
    at Re.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:118853)
    at Re.$provideDocumentColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:130539)
    at u.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:5502)
    at u.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:5268)
    at u.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:4323)
    at u.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:3440)
    at o.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:2227)
    at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
    at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:876)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:14173)
    at o.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:8018)
    at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
    at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:876)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:14173)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:6298)
    at MessagePortMain.emit (node:events:517:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
    at Object.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by neodisk17** [comment]
Hi @lethefrost , Could you share the file that's causing the error? It would make debugging easier.

**Comment by neodisk17** [comment]
Hi @lethefrost , thanks for the details.
After checking, it seems like this issue is happening from v1.2.0, I will check the cause of it and try to fix that as soon as possible

**Comment by neodisk17** [comment]
Hi @lethefrost , this issue has been fixed.
To support this package, please consider giving a star rating on the following platforms:

[GitHub](https://github.com/neodisk17/vscode-ext-flutter-color-viewer)
[Visual Studio Code Marketplace](https://marketplace.visualstudio.com/items?itemName=circlecodesolution.ccs-flutter-color)
[Open VSX](https://open-vsx.org/extension/circlecodesolution/ccs-flutter-color)

Thank you! 🌟
